# (c) Copyright IBM Corporation 2021
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
###############################################################################
# Contributed by the Ansible Content for IBM Z Team
#
# Changelog
#  All notable changes to this sample will be documented in this playbook
#
# 2021-01-31
#  - Released initial version
###############################################################################
# This sample playbook demonstrates basic usage of the cmci_get module
# included in the ibm.ibm_zos_cics collection
#
# Usage:
#  ansible-playbook report.yml
#
# Notes:
#  This sample playbook demonstrates how to use the cmci_get module from the
#  ibm.ibm_zos_cics collection to retrieve operational data from running CICS
#  regions. This example, retrieves information corresponding to the CICSRGN
#  resource table, but can be adapted to retrieve information about any of the
#  resource tables supported by CPSM. The retrieved information is written to a
#  csv file, suitable for opening as a spreadsheet.  This sample additionally
#  shows how to automate installation of pre-requisites for the CMCI modules.
#
# Requirements:
#   IBM z/OS CICS collection 1.0.0 or later
###############################################################################
---
- name: CICS CMCI Report

  hosts: "localhost"
  gather_facts: false

  vars:
    attributes:
      - eyu_cicsname
      - release
      - jobid
      - totltasks

  tasks:
    ############################################################################
    # Install module dependencies
    ############################################################################
    - name: Make sure CMCI module dependencies are installed
      ansible.builtin.pip:
        name:
          - requests
          - xmltodict
          - typing;python_version<"3.5"

    ############################################################################
    # Get information about CICS regions from the supplied context, using CMCI
    ############################################################################
    - name: Get information about CICS regions
      ibm.ibm_zos_cics.cmci_get:
        scheme: "https"
        insecure: true
        type: "CICSRegion"
        context: "<PLEX_Context>"
        cmci_host: "<HOST>"
        cmci_port: <PORT>
        cmci_cert: "<location>/hsbc_client_cert.pem"
        cmci_key: "<location>/hsbc_client_key.pem"
      register: result

    ############################################################################
    # Print the response from CMCI to the log - useful to see attribute names!
    ############################################################################
    # - debug:
    #         msg: '{{ result }}'

    ############################################################################
    # Write the report csv file using a template
    ############################################################################
    - name: Create CSV report from template
      ansible.builtin.template:
        src: csv.j2
        dest: report.csv
        mode: u+rw
